Algoritmo "Cronometro"
// Disciplina   : [Lï¿½gica de Programaï¿½
// Professor   : Jailson
// Descrição   : Progama que faz a função do cronometro
// Autor(a)    : Kayk Messias Gomes
// Data atual  : 04/04/2024
Var
   contadora, contadoraS: inteiro


Inicio
   para contadora de 0 ate 59 passo 1 faca
        para contadoraS de 0 ate 59 passo 1 faca
        Escreval(contadora,": ", contadoraS)
        timer 333
        fimpara
   fimpara
   


Fimalgoritmo