Algoritmo "Calculo de area de um circulo"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Calcula area de um circulo
// Autor(a)    : Kayk Messias Gomes
// Data atual  : 20/03/2024
Var
// Seção de Declarações das variáveis 
raio: inteiro
area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o valor inteiro do raio do circulo: ")
Leia(raio)

area<-PI*raio
escreval(area)

Fimalgoritmo